name: aklny
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  easy_localization: ^3.0.0
  responsive_framework: ^0.1.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  simple_shadow: ^0.2.0
  dots_indicator: ^2.0.0
  carousel_slider: ^2.3.1
  drawerbehavior: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/langs/
  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/SF UI Display/sf-ui-display-light.otf
          weight: 300
        - asset: assets/fonts/SF UI Display/sf-ui-display-regular.otf
          weight: 400
        - asset: assets/fonts/SF UI Display/sf-ui-display-medium.otf
          weight: 500
        - asset: assets/fonts/SF UI Display/sf-ui-display-bold.otf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700

