name: aklny
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.23.0+1
  easy_localization: ^3.0.0
  pin_code_fields: ^7.3.0
  responsive_framework: ^0.1.4
  shared_preferences: ^2.0.7
  simple_shadow: ^0.2.0
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  drawerbehavior: ^2.2.1
  flutter_advanced_drawer: ^1.2.4
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  dio: ^4.0.1
  pretty_dio_logger: ^1.1.1
  dio_firebase_performance: ^0.3.0
  flrx_validator: ^0.5.0
  fluttertoast: ^8.0.8



  #firebase
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_messaging: ^10.0.8
  sms_autofill: ^2.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/langs/
  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/SF UI Display/sf-ui-display-light.otf
          weight: 300
        - asset: assets/fonts/SF UI Display/sf-ui-display-regular.otf
          weight: 400
        - asset: assets/fonts/SF UI Display/sf-ui-display-medium.otf
          weight: 500
        - asset: assets/fonts/SF UI Display/sf-ui-display-bold.otf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
    - family: Viner
      fonts:
        - asset: assets/fonts/Viner Hand ITC/Viner Hand ITC.ttf
          weight: 400

